<?php

// @codingStandardsIgnoreFile
/**
 * @var \PensoPay\Gateway\Block\Info $block
 * @see \PensoPay\Gateway\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
?>
<?= $block->escapeHtml($block->getMethod()->getTitle()) ?>

<?php
$payment = $block->getInfo();

$transactionId = $payment->getLastTransId();
//get object manager
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$paymentFactory = $objectManager->get(\PensoPay\Gateway\Model\PaymentFactory::class);
$paymentAdapter = $objectManager->get(\PensoPay\Gateway\Model\Adapter\PensoPayAdapter::class);
$pensoPayment = $paymentFactory->create();
$pensoPayment->load($payment->getOrder()->getIncrementId(), 'order_id');
$paymentInfo = $paymentAdapter->getPayment($transactionId);
$pensoPayment->importFromRemotePayment($paymentInfo);
$pensoPayment->save();

if ($payment !== null): ?>
    <table border="0">
        <?php if ($payment->getLastTransId()): ?>
            <tr>
                <td><?= __('Transaction ID:'); ?></td>
                <td><?= $payment->getLastTransId(); ?></td>
            </tr>
        <?php endif; ?>
        <tr>
            <td><?= __('Card Type:') ?></td>
            <?php
                $cardImagePath = sprintf('PensoPay_Gateway::images/pensopaypayment/%s.png', $payment->getCcType() ?? '');
                $cardImageUrl = $this->getViewFileUrl($cardImagePath);
            ?>
            <td>
                <img src="<?= $cardImageUrl; ?>" width="40" alt="<?= $payment->getCcType() ?? '' ?>" />
            </td>
        </tr>
        <tr>
            <td><?= __('Currency:'); ?></td>
            <td><?= $payment->getAdditionalInformation()['currency'] ?? ''; ?></td>
        </tr>
        <tr>
            <td><?= __('Card number:'); ?></td>
            <td><?= implode(' ', str_split(sprintf('%sXXXXXX%s', $payment->getAdditionalInformation()['bin'] ?? '', str_replace('xxxx-', '', $payment->getCcLast4())), 4)); ?></td>
        </tr>

        <tr>
            <td><?= __('Acquirer:'); ?></td>
            <td><?= $payment->getAdditionalInformation()['acquirer'] ?? ''; ?></td>
        </tr>

        <tr>
            <td><?= __('Is 3D Secure:'); ?></td>
            <td><?= $payment->getAdditionalInformation()['is_3d_secure'] ?? '' ? __('Yes') : __('No'); ?></td>
        </tr>
    </table>
    <br />
<?php else: ?>
    <br />
    <?= __('Der er endnu ikke registreret nogen betaling for denne ordre!'); ?>
    <br />
<?php endif; ?>

<?= $block->getChildHtml() ?>
