<?php

use Magento\Checkout\Helper\Cart;
use Pensopay\Gateway\Helper\Viabill;

$viabillHelper = $this->helper(Viabill::class);
$checkoutHelper = $this->helper(Cart::class);
?>
<div class="checkout-viabill" style="display: none;">
    <?= $viabillHelper->renderViabillPrice('payment', round($checkoutHelper->getQuote()->getGrandTotal(), 2), '.checkout-index-index|.grand.totals span.price') ?>
</div>
